sudo: required
language: node_js
node_js:
  - 16
services:
  - docker
before_install:
  - docker build -t jason8746/node:1.0 -f Dockerfile.dev .
script:
  - docker run -e CI=true jason8746/node:1.0 npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "react-app-travis" ### Your EB App name
  env: "React-app-travis-env-1" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-ap-southeast-2-044530424430" ### S3 bucket name
  bucket_path: "travis-ela" ### S3 folder name under S3 bucket above
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
